### ISSUE TITLE
Create a logging function

### ISSUE THREAD

**Issue by wizedkyle** [wizedkyle/sumocli#1]
The application needs to output a log file to a OS specific temp path and output logs through the execution of the application.

# Basic Functionality

* Needs to create a new log file or append to one if it already exists
* Log key application processes
* Log verbose API responses

# Current Logging
<img width="430" alt="Screen Shot 2020-09-19 at 11 51 08 am" src="https://user-images.githubusercontent.com/58360154/93656520-6ff69900-fa6e-11ea-8506-c3aec4765ff8.png">

**Comment by jburger** [comment]
@wizedkyle I'll give this a go!
